# --- Backend services -------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/ankita-test-1/azureaks.git
      targetRevision: main
      path: gitops/k8s/backend
    - repoURL: https://github.com/ankita-test-1/azureaks.git
      targetRevision: main
      path: gitops
      directory:
        include: "secrets.yml"
    - repoURL: https://github.com/ankita-test-1/azureaks.git
      targetRevision: main
      path: gitops/k8s/database
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# --- Frontend ---------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ankita-test-1/azureaks.git
    targetRevision: main
    path: gitops/k8s/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# --- Cilium Gateway API resources -------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ankita-test-1/azureaks.git
    targetRevision: main
    path: gitops/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
