apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: boutique-gateway
  namespace: boutique
spec: 
  gatewayClassName: cilium
  infrastructure:
    annotations: service.beta.kubernetes/azure-load-balancer-internal: "true"
  listeners:
    -name: http
     protocol: HTTP
     port: 80
     hostname: aksboutique.
    
    -name: https
     protocol: HTTPS
     port: 443
     hostname: aksboutique.
     tls:
       certificateRefs:
         -kind: Secret
          name: boutique-tls-cert
     allowedRoutes:
       namespaces:
         from: Same
    
