name: Boutique CI Pipeline

on:
  workflow_dispatch:

env:
  AZURE_CLIENT_ID: 36572c9f-4e5c-4efb-bb7b-db64021e4dc0
  AZURE_TENANT_ID: 89829357-4296-4e69-b714-fffa2fa6d8b1
  AZURE_SUBSCRIPTION_ID: 19956185-59a5-4243-b32d-572e96134d6e
  ACR_NAME: aksregistryshopping     
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write  
  contents: read  

jobs:
  build-and-push:
    runs-on: self-hosted

    strategy:
      matrix:
        service:
          - auth
          - gateway
          - orders
          - order-service
          - product-service
          - user-service
          - frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker Image
        run: |
          if [ "${{ matrix.service }}" == "frontend" ]; then
            BUILD_PATH="projects/boutique-microservices/frontend"
          else
            BUILD_PATH="projects/boutique-microservices/backend/services/${{ matrix.service }}"
          fi

          echo "Building from $BUILD_PATH"

          docker build \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service }}:${{ env.IMAGE_TAG }} \
            $BUILD_PATH

      - name: Push Docker Image
        run: |
          IMAGE_URI=${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service }}:${{ env.IMAGE_TAG }}
          echo "Pushing $IMAGE_URI"
          docker push $IMAGE_URI

 
